name: Secret workflow
run-name: ${{ github.actor }} is secretely posting
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install nodejs
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: |
          npm install
          npm ci
          npm run build
      - name: Run tests
        run: |
          npm run test
      # on se connecte au registre Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # on construit l'image Docker
      - name: Build Docker image
        run: |
          docker build -t sysinfo-api:latest
          docker tag sysinfo-api:0.0.1 ${{ secrets.DOCKER_USERNAME }}/sysinfo-api:0.0.1
      - name: Push Docker image
        run: |
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/sysinfo-api:${{ github.sha }}
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/sysinfo-api:latest
